### conf/train.yaml

#
# Train Hyperparameters
#
run_name : Hydra_test
epochs : 1
batch_size : 1
dataset_path : "/mnt/qb/baumgartner/rawdata/BraTS2021_Training_Data"
start_lr : 2.0e-5
target_lr : 1.0e-4
warmup_steps: 0.05
ema_decay: 0.995

train_continue : False
model : 
ema_model :
opt :

path_to_csv : 
start_ckpt : 50
save_ckpt : 4
num_images : 1



#
# Model Hyperparameters
#
size : 128
channels : 4


#
# Diffusion Hyperparameters
#
length: 1000
beta_start: 1.0e-4
beta_end: 0.02


#
# Noise type
#
pyramid : False
simplex : False